apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-selector: spark-30dce1fed3424c8d8ae386eb781d150b
    spark-role: driver
    sparkoperator.k8s.io/app-name: spark-pi
    sparkoperator.k8s.io/submission-id: fd10578e-abea-44c0-8bbd-f3aa27df898f
  name: promtail
spec:
  volumes:
  - name: logs
    emptyDir: {}        
  - name: promtail-config-tmpl
    configMap:
      name: promtail-tmpl
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels      
  containers:
  - name: alpine
    image: alpine
    args:
    - sh
    - -c
    - 'while [ 1 ]; do D=`date -Iseconds`; echo "$D INFO test message"|tee -a /logs/test.log; sleep 3; done'
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    volumeMounts:
    - name: logs
      mountPath: /logs
  - name: promtail-container
    image: allanhung/protail:20200417
    args:
    - /tmpl/promtail.yaml.tmpl
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name      
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    volumeMounts:
    - name: logs
      mountPath: /ext/logs
    - name: promtail-config-tmpl
      mountPath: /tmpl
    - mountPath: /podinfo
      name: podinfo
